version: '2'

networks:
  prodnetwork:
    driver: bridge

services:

 sonar:
  image: sonarqube:9.9.0-community
  ports:
   - "9000:9000"
  networks:
    - prodnetwork

 sonar-scanner:
  build: ./sonar-scanner
  networks:
    - prodnetwork
  depends_on:
    - sonar
  environment:
   - SONAR_HOST_URL=http://sonar:9000
   - SONAR_PROJECT_KEY=hello:world
   - SONAR_PROJECT_NAME=HelloWorld
   - SONAR_PROJECT_VERSION=0.1
 
